version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"  # Map the host port to the same container port
    environment:
      - ENVIRONMENT=development
      - PORT=8000
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app