version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

