version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"  # Map the host port to the same container port
    environment:
      - ENVIRONMENT=development
      - PORT=${PORT:-8000}
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app