version: "3.8"

services:
  app:
    build: .
    expose:
      - "8000"  # Expose port to internal network, but don’t publish it
    environment:
      - ENVIRONMENT=development
      - PORT=8000
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount nginx.conf file