name: Deploy to Heroku

on:
 push:
   branches: [ main ]

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Install Heroku CLI
       run: |
         curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
     - name: Set DOCKER_BUILDKIT
       run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
     - name: Build, tag, and push image to Heroku Container registry
       run: |
         docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
         heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
     - name: Release application
       run: |
         heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
