name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with: 
          python-version: "3.10"
      - name: Clear pip cache
        run: rm -rf ~/.cache/pip  # Clear cache to prevent conflicts
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx  # Ensure these are installed last
      - name: Debug installed packages
        run: pip list  # Check if pytest is installed
      - name: Test with pytest
        run: pytest
