name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Heroku Container Registry
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Release application
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
